USE Troho;

INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (1, 'The Lorenzo', '325 W Adams Blvd', 'Luxurious apartments slightly far from USC campus.', './img/LocationImages/lorenzo.jpeg', './img/LocationFloorplans/lorenzo.png', '34.027462', '-118.272988', 20, 10);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (1, 'Icon Plaza', '3584 S Figueroa St', 'Small apartment series across the street from campus.', './img/LocationImages/iconplaza.jpeg', './img/LocationFloorplans/iconplaza.png', '34.0184869', '-118.2824651', 5, 3);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (1, 'Tuscany', '3770 S. Figueroa St.', 'Large and quite luxurious apartments right off the southeast corner of USC.', './img/LocationImages/tuscany.jpeg', './img/LocationImages/tuscany.png', '34.017273', '-118.28239', 7, 4);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (1, 'Gateway Apartments', '124 30th St', 'A very convenient apartment series just north of campus.', './img/LocationImages/gateway.jpeg', './img/LocationFloorplans/gateway.jpeg', '34.022865', '-118.279812', 6, 4);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (1, 'Troy East', '3025 Royal St', 'Troy East is a large apartment building that is very popular with returning undergraduates. The building features multiple configurations that offer the privacy of a two person apartment or the economy and social benefits of a five person, two-bedroom apartment. The five person apartments have a bedroom for two residents and a bedroom for three.', './img/LocationImages/troyeast.jpg', './img/LocationFloorplans/troyeast.jpg', '34.0255435', '-118.2819783', 10, 5);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (1, 'Cardinal Gardens', '3131 S. McClintock Ave', 'Cardinal Gardens is an extremely popular apartment complex consisting of nine individual townhouse-style buildings connected by winding, tree-lined walkways. This energetic community is home to upperclassmen, as well as freshmen, housed in fully furnished one and two-bedroom apartments. Each apartment has a full kitchen and bathroom and a spacious, air-conditioned living room. All units were recently upgraded with new furniture and laminate flooring.', './img/LocationImages/cardinalgardens.jpg', './img/LocationFloorplans/cardinalgardens.jpg', '34.026087', '-118.287176', 6, 4);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (2, 'Pardee Tower', '614 Hellman Way', 'Pardee Tower was built as part of USC’s commitment to the Olympic Village for the 1984 Summer Games. This eight-floor coed residence hall, close to Doheny Library and McCarthy Quad, alternates genders by floor. Each floor has 18 double rooms, a common bathroom and a laundry facility.', './img/LocationImages/pardee.jpg', './img/LocationFloorplans/pardee.jpg', '34.020011', '-118.282598', 3, 1);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (2, 'Trojan Hall', '615 Childs Way', 'Three-story Trojan Hall is one of the four residence halls that make up the South Area Residential College freshman living area. It\'s close to Popovich Café, the Ground Zero coffeehouse and the Leavey and Doheny libraries.', './img/LocationImages/trojanhall.jpg', './img/LocationFloorplans/trojanhall.jpg', '34.0193411', '-118.2824477', 3, 1);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (2, 'New Residential College', '635 McCarthy Way', 'New/North’s typical resident is an active scholar looking for a sense of community and modern conveniences, who wants the traditional residence hall experience for their first year at college.', './img/LocationImages/new.jpg', './img/LocationFloorplans/new.jpg', '34.021250', '-118.281289', 4, 2);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (2, 'North Residential College', '635 McCarthy Way', 'Despite its name, New Residential College is one of USC\'s oldest housing facilities, a place steeped in tradition that combines classic residence hall architecture with modern amenities and forward-looking programs.', './img/LocationImages/north.jpg', './img/LocationFloorplans/new.jpg', '34.021250', '-118.281289', 4, 2);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (3, 'Widney Alumni House', '635 Childs Way', 'While this isn\'t an actual house we can live in, we can pretend..', './img/LocationImages/widney.jpg', './img/LocationFloorplans/new.jpg', '34.019525', '-118.282866', 2, 1);
INSERT INTO HousingLocations (housingType, locationName, textAddress, description, imageURLs, floorplanURLs, gpsLatitude, gpsLongitude, minutesWalking, minutesBiking) VALUES (3, 'SAL', '920 W 37th Pl', 'We\'ve spent enough time on this project to live on campus..', './img/LocationImages/sal.jpg', './img/LocationFloorplans/new.jpg', '34.019493', '-118.289539', 2, 1);
SELECT * FROM HousingLocations;

INSERT INTO Users (name, housingKey, email, facebookID, imageURL, isAdmin, verifiedEmail) VALUES ('Steve Johnson', 1, 'steve@asdf.asdf', '2903i4lkjasdf', 'http://sparksc.org/img/coreteam/NeelBhoopalam.jpg', false, true);
INSERT INTO Users (name, housingKey, email, facebookID, imageURL, isAdmin, verifiedEmail) VALUES ('Johnny Wang', 2, 'john@asdf.asdf', '12rehfdsu2j34f1d4','http://sparksc.org/img/coreteam/NeelBhoopalam.jpg', false, true);
INSERT INTO Users (name, housingKey, email, facebookID, imageURL, isAdmin, verifiedEmail) VALUES ('Tommy Trojan', 2, 'john@asdf.asdf', '2weuhfdsu2j34f1d4','http://sparksc.org/img/coreteam/NeelBhoopalam.jpg', false, false);
SELECT * FROM Users;

INSERT INTO Friends (facebookID, friendID) VALUES ('2weuhfdsu2j34f1d4', '12rehfdsu2j34f1d4');
INSERT INTO Friends (facebookID, friendID) VALUES ('12rehfdsu2j34f1d4', '2weuhfdsu2j34f1d4');
SELECT * FROM Friends;

INSERT INTO Surveys (facebookID, managementSurveyScore, amenitiesSurveyScore, locationSurveyScore, noiseSurveyScore, communityChillFactorSurveyScore) VALUES ('12rehfdsu2j34f1d4', '5', '5', '5', '5', '5');
INSERT INTO Surveys (facebookID, managementSurveyScore, amenitiesSurveyScore, locationSurveyScore, noiseSurveyScore, communityChillFactorSurveyScore) VALUES ('2weuhfdsu2j34f1d4', '10', '10', '5', '0', '0');
SELECT * FROM Surveys;

INSERT INTO Reviews (housingKey, facebookID, textComment, managementScore, amenitiesScore, locationScore, noiseScore, communityChillFactorScore, timeWritten) VALUES ('1', '2weuhfdsu2j34f1d4', 'my comment', '5', '5', '5', '4', '5', now());
INSERT INTO Reviews (housingKey, facebookID, textComment, managementScore, amenitiesScore, locationScore, noiseScore, communityChillFactorScore, timeWritten) VALUES ('4', '2weuhfdsu2j34f1d4', 'I love Gateway, its awesome!', '5', '5', '5', '4', '5', now());
SELECT * FROM Reviews;
